version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.app
    container_name: crm_topo_app
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/localhost/htdocs/app
    ports:
      - 18080:8080
    depends_on:
      - db

  db:
    image: mariadb:10.3.35
    container_name: crm_topo_db
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root